version: '3.9'
services:
  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orders_db
    ports:
      - "5432:5432"

  app:
    image: my-challenge:latest
    container_name: my-app
    env_file:
      - teste.env
    ports:
      - "8080:8080"
      - "50051:50051"
    depends_on:
      - db
